apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.imageProcessor.name }}-deployment
spec:
  replicas: {{ .Values.imageProcessor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.imageProcessor.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.imageProcessor.name }}
    spec:
      containers:
        - name: {{ .Values.imageProcessor.containerName }}
          image: "{{ .Values.imageProcessor.image.registry }}:{{ .Values.imageProcessor.image.tag }}"
          imagePullPolicy: {{ .Values.imageProcessor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.imageProcessor.containerPort.http }}
              protocol: TCP
          resources: {{ toYaml .Values.imageProcessor.resources | nindent 12 }}
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.imageProcessor.name }}-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.imageProcessor.name }}-secret
                  key: AMQP_PASSWORD
            - name: AMQP_EXCHANGE
              value: {{ .Values.imageProcessor.config.amqpExchange | quote }}
            - name: AMQP_HOSTNAME
              value: {{ .Values.imageProcessor.config.amqpHostname | quote }}
            - name: AMQP_QUEUE
              value: {{ .Values.imageProcessor.config.amqpQueue | quote }}
