apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: conv-service
  template:
    metadata:
      labels:
        component: conv-service
    spec:
      containers:
      - name: conv-service
        image: ghcr.io/reixxen/conv-service:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
          requests:
            memory: "250Mi"
            cpu: "100m"
        ports:
          - containerPort: 3000
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: username
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: password
          - name: AMQP_HOSTNAME
            value: rabbitmq-clusterip
          - name: AMQP_QUEUE
            value: converter-queue
