apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.containerName }}
          image: "{{ .Values.app.image.registry }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort.http }}
              protocol: TCP
          resources: {{ toYaml .Values.app.resources | nindent 12 }}
          env:
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: VITE_DOMAIN
