apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}-deployment
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.rabbitmq.name }}
    spec:
      containers:
        - name: {{ .Values.rabbitmq.containerName }}
          image: "{{ .Values.rabbitmq.image.registry }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.containerPort.amqp }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.rabbitmq.containerPort.management }}
              protocol: TCP
            - name: cluster
              containerPort: {{ .Values.rabbitmq.containerPort.cluster }}
              protocol: TCP
          resources: {{ toYaml .Values.rabbitmq.resources | nindent 12 }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.name }}-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.name }}-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.name }}-secret
                  key: RABBITMQ_ERLANG_COOKIE
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: {{ .Values.rabbitmq.name }}-data
              mountPath: /var/lib/rabbitmq/data
      volumes:
        - name: {{ .Values.rabbitmq.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.rabbitmq.name }}-pvc
